version: '3'
networks:
  default:
    external:
      name: cic

services:
  rabbit1:
    hostname: rabbit1
    privileged: true
    image: ${CIC_COURSEWARE_IMAGE}:${CIC_COURSEWARE_VERSION}
    command: /sbin/init
    ports: ["15672:15672"]


  rabbit2:
    hostname: rabbit2
    privileged: true
    image: ${CIC_COURSEWARE_IMAGE}:${CIC_COURSEWARE_VERSION}
    command: /sbin/init

  rabbit3:
    hostname: rabbit3
    privileged: true
    image: ${CIC_COURSEWARE_IMAGE}:${CIC_COURSEWARE_VERSION}
    command: /sbin/init


  newserver:
    hostname: new_server
    privileged: true
    image: ${CIC_COURSEWARE_IMAGE}:${CIC_COURSEWARE_VERSION}
    command: /sbin/init