---
- name: super loop
  hosts: all
  vars:
    list_of_packages:
      Ubuntu:
      - git
      - ftp
      - apache2
      CentOS:
      - git
      - ftp
      - httpd
  tasks:
  - include: sub_tasks.yml group_name="{{item['key']}}" users="{{item['value']}}"
    loop: "{{ list_of_packages| dict2items }}"




