---
- name: super loop
  hosts: all
  vars:
    list_of_packages:
      Ubuntu:
      - git
      - ftp
      - apache2
      CentOS:
      - git
      - ftp
      - httpd
  tasks:
  - name: print the list
    block:
    - apt:
        name: "{{item}}"
        state: present
      loop: "{{list_of_packages[ansible_distribution]}}"
      when: ansible_distribution=="Ubuntu"
    - yum:
        name: "{{item}}"
        state: present
      loop: "{{list_of_packages[ansible_distribution]}}"
      when: ansible_distribution=="CentOS"


